curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_1.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_2.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_3.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_4.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_5.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_6.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_7.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_8.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_9.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_10.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_11.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_12.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_13.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_14.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_15.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_16.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_17.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_18.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_19.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_20.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_21.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_22.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_23.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_24.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_25.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_26.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_27.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_28.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_29.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_30.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_31.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_32.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_33.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_34.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_35.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_36.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_37.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_38.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_39.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_40.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_41.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_42.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_43.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_44.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_45.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_46.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_47.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_48.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_49.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_50.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_51.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_52.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_53.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_54.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_55.json
curl -XPOST https://search-nsinha-pc-6x4ctzvktckl5u3rbktxjduoj4.us-east-2.es.amazonaws.com/_bulk --data-binary @data_56.json